name: dfm_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip>=19.2.3
  - pip:
    - hydrolib-core>=0.4.0
  - scipy
  - numpy<1.24
  - matplotlib
  - pandas
  - shapely
  - cartopy
  - pyepsg
  - geopandas
  - contextily
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - xugrid>=0.2.0
  - cdsapi
  - pydap
    
