name: dfm_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip>=19.2.3
  - scipy
  #install older numpy version #to avoid "SystemError: initialization of _internal failed without raising an exception" in #57 to #61. https://stackoverflow.com/questions/74947992/how-to-remove-the-error-systemerror-initialization-of-internal-failed-without
  - numpy<1.24
  - matplotlib
  - pandas
  - shapely>=1.7.0
  - cartopy
  - pyepsg
  - geopandas
  - contextily
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - xugrid>=0.2.1
  - cdsapi
  - pydap
  - pip:
    - hydrolib-core>=0.4.0
    - pytest
    - pytest-cov
    - jupyter
    - notebook
    - bumpversion
    - twine
