name: dfm_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip>=19.2.3
  - hydrolib-core>=0.4.0
  - scipy
  #install older numpy version #to avoid "SystemError: initialization of _internal failed without raising an exception" in #57 to #61. https://stackoverflow.com/questions/74947992/how-to-remove-the-error-systemerror-initialization-of-internal-failed-without
  - numpy<1.24
  - matplotlib
  - pandas
  - shapely
  - cartopy
  - pyepsg
  - geopandas
  - contextily
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - xugrid>=0.2.0
  - cdsapi
  - pydap
    
