name: dfm_tools_env
dependencies:
  - python=3.7
  - pip>=19.2.3
  - pip:
    - pytest>=5.0.1
    - spyder-kernels==0.*
    - bump2version>=0.5.11
    - wheel>=0.33.6
    - watchdog>=0.9.0
    - flake8>=3.7.8
    - tox>=3.14.0
    - coverage>=4.5.4
    - Sphinx>=1.8.5
    - twine>=1.14.0
    - Click>=7.0
    - pytest-runner>=5.1
    