name: dfm_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip>=19.2.3
  - shapely
  - cartopy
  - pyepsg
  - geopandas
  - contextily
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - xugrid
  - cdsapi
  - pydap
  - pip:
    - scipy
    - numpy
    - matplotlib
    - pandas
    - hydrolib-core>=0.3.1
    
