#TODO: add meshkernel>=2.0.2 (pip or conda?)
name: dfm_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip>=19.2.3
  #install older scipy version to avoid da.interp() issue: https://github.com/Deltares/dfm_tools/issues/287 and https://github.com/pydata/xarray/issues/7701
  - scipy<1.10.0
  #install older numpy version to avoid issue: https://github.com/Deltares/dfm_tools/issues/295
  - numpy<1.24.0
  - matplotlib
  - pandas
  - shapely>=1.7.0
  - cartopy
  - pyepsg
  - geopandas
  - contextily
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - xugrid>=0.2.1
  - cdsapi
  - pydap
  - pip:
    - hydrolib-core>=0.4.0
    - pytest
    - pytest-cov
    - jupyter
    - notebook
    - bumpversion
    - twine
