name: dfm_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip>=19.2.3
  - scipy<1.10.0
  - numpy
  - matplotlib
  - pandas<2.0.0
  - shapely>=1.7.0
  - cartopy
  - pyepsg
  - geopandas
  - contextily
  - xarray<2023.3.0
  - dask
  - netcdf4>=1.5.3
  - bottleneck
  - xugrid>=0.4.0
  - cdsapi
  - pydap>=3.3.0
  - pip:
    - hydrolib-core>=0.5.1
    - meshkernel>=2.0.2
