name: generate-documentation

on:
  push:
    branches:
    - main
  # pull_request:
    # branches:
    # - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    # the checkout action persists the passed credentials by default
    # subsequent git commands will pick them up automatically
    # works with PAT: https://stackoverflow.com/questions/69263843/how-to-push-to-protected-main-branches-in-a-github-action/72515781#72515781
    # more accurate is this description: https://stackoverflow.com/a/64078507/5578371
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.PAT}}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_dev.txt
    - name: list env contents
      run: |
        conda info
        conda list
        pip list
    - name: Generate documentation
      run: |
        pdoc --html dfm_tools -o docs --force --config sort_identifiers=False
    - name: Commit updated documentation
      run: |
        git config --global user.name 'veenstrajelmer'
        git config --global user.email "Jelmer.Veenstra@deltares.nl"
        git add docs/dfm_tools/*
        git commit -a -m "Updated documentation" --no-verify --allow-empty
        git push
