name: generate-documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: #Conda activation does not correctly work on sh. Please use bash.
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repos
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: dfm_tools_env
        environment-file: environment.yml
        channels: conda-forge
        python-version: 3.8
        auto-activate-base: false
    - name: test conda env
      run: |
        conda info
        conda list
    - name: install pdoc etc
      run: |
        python -m pip install pdoc3 pandoc
      #- name: install older numpy version #to avoid "SystemError: initialization of _internal failed without raising an exception" in #57 to #61. https://stackoverflow.com/questions/74947992/how-to-remove-the-error-systemerror-initialization-of-internal-failed-without
      #run: |
      #  python -m pip install "numpy<1.24"
    - name: Generate documentation
      run: |
        pdoc --html dfm_tools -o docs --force --config sort_identifiers=False
    - name: Commit updated documentation
      run: |
        git config --global user.name 'veenstrajelmer'
        git config --global user.email "Jelmer.Veenstra@deltares.nl"
        git add docs/dfm_tools/*
        git commit -a -m "Updated documentation" --no-verify
        git push
