name: generate-documentation

on:
  push:
    branches: [ master work_jelmer ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pdoc3 pandoc
        #conda env update --file environment.yml --name base
        conda create --name dfm_tools_env -c conda-forge python=3.8 shapely cartopy pyepsg geopandas contextily xarray dask netcdf4 bottleneck cdsapi motuclient -y
    - name: Generate documentation
      run: |
        conda activate dfm_tools_env
        pdoc --html dfm_tools -o docs --force --config sort_identifiers=False
    - name: Commit updated documentation
      run: |
        git config --global user.name 'veenstrajelmer'
        git add docs/dfm_tools/*
        git commit -a -m "Updated documentation" --no-verify
        git push
