name: generate-documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        # $CONDA/bin/conda env update --file environment.yml --name base
        #conda env update --file environment.yml --name base
        #conda update -n base -c defaults conda
        #conda install -c conda-forge shapely cartopy pyepsg geopandas contextily xarray dask netcdf4 bottleneck cdsapi motuclient "geos>=3.7.2" -y
        
        python -m pip install pdoc3 pandoc
        #pip install -r requirements.txt
        
        #conda update -n base -c defaults conda
        #conda env update --file environment.yml --name base
      
    - name: Generate documentation
      run: |
        pdoc --html dfm_tools -o docs --force --config sort_identifiers=False
    - name: Commit updated documentation
      run: |
        git config --global user.name 'veenstrajelmer'
        git add docs/dfm_tools/*
        git commit -a -m "Updated documentation" --no-verify
        git push
