name: generate-documentation

on:
  push:
    branches:
    - main
  # pull_request:
    # branches:
    # - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
        runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install flake8 pytest pytest-cov
        python -m pip install -r requirements.txt
        #python setup.py test
    - name: install pdoc etc
      run: |
        python -m pip install pdoc3 pandoc
      #- name: install older numpy version #to avoid "SystemError: initialization of _internal failed without raising an exception" in #57 to #61. https://stackoverflow.com/questions/74947992/how-to-remove-the-error-systemerror-initialization-of-internal-failed-without
      #run: |
      #  python -m pip install "numpy<1.24"
    - name: Generate documentation
      run: |
        pdoc --html dfm_tools -o docs --force --config sort_identifiers=False
    - name: Commit updated documentation
      run: |
        git config --global user.name 'veenstrajelmer'
        git config --global user.email "Jelmer.Veenstra@deltares.nl"
        git add docs/dfm_tools/*
        git commit -a -m "Updated documentation" --no-verify --allow-empty
        git push
