name: mkdocs-gh-deploy
on:
  push:
    branches:
      - main
      - 354-from-pdoc-to-mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements_dev.txt
      - run: mkdocs gh-deploy --force