---
name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['py310', 'py311', 'py312', 'py313', 'py314']
        os: [ubuntu-latest] #, windows-latest]

    name: py-${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: "v0.67.1"
          environments: ${{ matrix.python-version }}

      - name: List env contents
        run: |
          pixi list -e ${{ matrix.python-version }}

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pixi run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          pixi run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        env:
          CDSAPI_KEY: ${{ secrets.CDSAPI_KEY }}
          COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
          COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
        run: |
          pixi run --locked -e ${{ matrix.python-version }} test -m "not requireslocaldata"

      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
